### PR TITLE
new planet marvel universe

### PR DESCRIPTION
**Pull request by xaca**
@mozzadrella Can you help me please. :smiley_cat: with questions :question:

### CODE REVIEW

**Comment by ericdrosado** [comment]
👋 Hi @xaca! What can I help you with?

**Comment by xaca** [comment]
@ericdrosado Hello, I want to know how to add a pull request to a issue. Thank you. :sunglasses:

**Comment by ericdrosado** [comment]
@xaca : There are a few ways you can handle this. If you are interested in referencing a Pull Request (PR) in an issue, you can literally use `#` and the number of the PR. I created an issue for you as an example.

Another option is to install an open source project like the "hub" project: https://stackoverflow.com/questions/4528869/how-do-you-attach-a-new-pull-request-to-an-existing-issue-on-github . This will allow you to do everything from the command line.

Let me know if you have any additional questions.

**Comment by xaca** [comment]
@ericdrosado Ok, I have new things to test. Thank you for your quickly reply. :+1:

**Pull request closed without merging**
